stages:
- name: Build
  inputs:
  - type: git
    branch: master
    service: skitgitrepo
  jobs:
  - name: Build
    type: builder
    build_type: shell
    artifact_dir: ""
    curatedDockerImage: default
    script: |
      #!/bin/bash
      # uncomment to debug the script
      # set -x

      if [ "${ENABLED_CF}" == "false" ]; then
          echo "CF pipeline is disabled for this toolchain"
          exit 0
      fi

      function check_exit
      {
        rv=$?
        if [ $rv != 0 ]; then
            msg="Build Failed :spinning-siren:"
            echo "${msg}"
            source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
            exit 1
        else
            exit 0
        fi
      }

      trap 'check_exit' EXIT
      source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/build_cf.sh")
  properties:
  - name: GIT_URL
    type: text
    value: ${GIT_URL}
  - name: DEVX_SKIT_ASSETS_GIT
    type: text
    value: IBM/devex-skit-assets
  - name: DEVX_SKIT_ASSETS_GIT_BRANCH
    type: text
    value: master
  - name: DEVX_SKIT_ASSETS_GIT_URL
    type: text
    value: https://github.com/${DEVX_SKIT_ASSETS_GIT}.git
  - name: DEVX_SKIT_ASSETS_GIT_URL_RAW
    type: text
    value: https://raw.githubusercontent.com/${DEVX_SKIT_ASSETS_GIT}/${DEVX_SKIT_ASSETS_GIT_BRANCH}
  - name: DEVX_SKIT_ASSETS_GIT_URL_CODE
    type: text
    value: https://codeload.github.com/${DEVX_SKIT_ASSETS_GIT}/tar.gz/${DEVX_SKIT_ASSETS_GIT_BRANCH}
  - name: DEPLOY_TARGET
    type: text
    value: cf
  - name: ENABLED_CF
    type: text
    value: ${ENABLED_CF}
  - name: SLACK_WEBHOOK
    type: text
    value: ${SLACK_WEBHOOK}
  - name: OWNER_SLACK_CHANNEL
    type: text
    value: ${OWNER_SLACK_CHANNEL}
  - name: PAGERDUTY_API_URL
    type: text
    value: ${PAGERDUTY_API_URL}
  - name: PAGERDUTY_EVENTS_API_URL
    type: text
    value: ${PAGERDUTY_EVENTS_API_URL}
  - name: PAGERDUTY_API_TOKEN
    type: secure
    value: ${PAGERDUTY_API_TOKEN}
  - name: PAGERDUTY_SVC_NAME
    type: secure
    value: ${PAGERDUTY_SVC_NAME}
  - name: ENABLE_PD_ALERTS
    type: text
    value: "true"
  triggers:
  - events: '{"push":true,"pull_request":false,"pull_request_closed":false}'
    type: git
- name: Deploy
  inputs:
  - type: job
    job: Build
    stage: Build
  jobs:
  - name: Rolling Deploy
    type: deployer
    deploy_type: cf
    curatedDockerImage: default
    script: |
      #!/bin/bash
      # uncomment to debug the script
      # set -x

      if [ "${ENABLED_CF}" == "false" ]; then
          echo "CF pipeline is disabled for this toolchain"
          exit 0
      fi

      function check_exit
      {
        rv=$?
        if [ $rv != 0 ]; then
            msg="Deploy Failed :spinning-siren:"
            echo "${msg}"
            source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
            exit 1
        else
            exit 0
        fi
      }

      trap 'check_exit' EXIT
      source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/deploy_cf.sh")
    target:
      api_key: ${API_KEY}
      application: ${APP_NAME}-monitored-cf
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      region_id: ${PROD_REGION_ID}
  properties:
  - name: buildProperties
    type: file
    value: build.properties
  - name: ENABLE_PD_ALERTS
    type: text
    value: "true"
  triggers:
  - type: stage
- name: Verification
  inputs:
  - type: job
    job: Build
    stage: Build
  jobs:
  - name: Experience Test
    type: deployer
    deploy_type: cf
    curatedDockerImage: default
    script: |-
      #!/bin/bash
      # uncomment to debug the script
      # set -x

      if [ "${ENABLED_CF}" == "false" ]; then
          echo "CF pipeline is disabled for this toolchain"
          exit 0
      fi

      source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/verification_experience_test.sh")
    target:
      api_key: ${API_KEY}
      application: ${APP_NAME}-monitored-cf
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      region_id: ${PROD_REGION_ID}
  properties:
  - name: buildProperties
    type: file
    value: build.properties
  - name: ENABLE_PD_ALERTS
    type: text
    value: "true"
  triggers:
  - type: stage
properties: []
