---
inputs:
  - type: git
    service: ${PIPELINE_REPO}
    branch: ${PIPELINE_REPO_BRANCH}
    path: .pipeline/cf
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${TEKTON_CATALOG_REPO_BRANCH}
    path: git
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${TEKTON_CATALOG_REPO_BRANCH}
    path: cloudfoundry
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${TEKTON_CATALOG_REPO_BRANCH}
    path: toolchain
triggers:
  - type: git
    name: commit-push
    eventListener: ${GIT_COMMIT_EVENT_LISTENER_NAME}
    service: ${GIT_REPO}
    branch: master
    events: { "push": true }
  - type: manual
    name: manual-run
    eventListener: manual-run
    properties: []
properties:
  - type: text
    name: cf-app
    value: ${APP_NAME}-monitored-cf
  - type: text
    name: APP_NAME
    value: ${APP_NAME}
  - type: text
    name: cf-org
    value: ${PROD_ORG_NAME}
  - type: text
    name: cf-space
    value: ${PROD_SPACE_NAME}
  - type: text
    name: region
    value: ${PROD_REGION_ID}
  - type: secure
    name: toolchain-apikey
    value: ${API_KEY}
  - type: secure
    name: apikey
    value: ${API_KEY}
  - name: GIT_URL
    value: ${GIT_URL}
    type: text
  - name: PROD_CLUSTER_NAMESPACE
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: PROD_CLUSTER_NAME
    value: ${PROD_CLUSTER_NAME}
    type: text
  - name: RESOURCE_GROUP
    value: ${PROD_RESOURCE_GROUP}
    type: text
  - name: DEVX_SKIT_ASSETS_GIT
    value: IBM/devex-skit-assets
    type: text
  - name: DEVX_SKIT_ASSETS_GIT_RELEASE
    value: ${DEVX_SKIT_ASSETS_GIT_RELEASE}
    type: text
  - name: DEVX_SKIT_ASSETS_GIT_URL
    value: https://github.com/${DEVX_SKIT_ASSETS_GIT}.git
    type: text
  - name: DEVX_SKIT_ASSETS_GIT_URL_RAW
    value: https://github.com/${DEVX_SKIT_ASSETS_GIT}/raw/${DEVX_SKIT_ASSETS_GIT_RELEASE}
    type: text
  - name: DEVX_SKIT_ASSETS_GIT_URL_CODE
    value: https://codeload.github.com/${DEVX_SKIT_ASSETS_GIT}/tar.gz/${DEVX_SKIT_ASSETS_GIT_RELEASE}
    type: text
  - name: ENABLED_CF
    value: ${ENABLED_CF}
    type: text
  - name: ENABLED_HELM
    value: ${ENABLED_HELM}
    type: text
  - name: DEVX_SLACK_CHANNEL_WEBHOOK
    value: ${DEVX_SLACK_CHANNEL_WEBHOOK}
    type: secure
  - name: OWNER_SLACK_CHANNEL_WEBHOOK
    value: ${OWNER_SLACK_CHANNEL_WEBHOOK}
    type: secure
  - name: PAGERDUTY_API_URL
    value: ${PAGERDUTY_API_URL}
    type: text
  - name: PAGERDUTY_EVENTS_API_URL
    value: ${PAGERDUTY_EVENTS_API_URL}
    type: text
  - name: PAGERDUTY_API_TOKEN
    value: ${PAGERDUTY_API_TOKEN}
    type: secure
  - name: PAGERDUTY_SVC_NAME
    value: ${PAGERDUTY_SVC_NAME}
    type: secure
  - name: ENABLE_PD_ALERTS
    value: ${ENABLE_PD_ALERTS}
    type: text
  - name: SKIT_REG_ENDPOINT
    value: ${SKIT_REG_ENDPOINT}
    type: text
  - name: SKIT_REG_AUTH_TOKEN
    value: ${SKIT_REG_AUTH_TOKEN}
    type: secure
  - name: DEPLOY_TARGET
    value: cf
    type: text
settings:
  slackEnabled: true