---
inputs:
  - type: git
    branch: ${PIPELINE_REPO_BRANCH}
    service: ${PIPELINE_REPO}
    path: .pipeline/helm
  - type: git
    branch: ${PIPELINE_REPO_BRANCH}
    service: ${PIPELINE_REPO}
    path: tasks/skit-verification
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: git
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: container-registry
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: master
    path: kubernetes-service
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: master
    path: toolchain
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: master
    path: devops-insights
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: linter
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: tester
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: utils
triggers:
  - type: git
    name: commit-push
    eventListener: ${GIT_COMMIT_EVENT_LISTENER_NAME}
    service: ${GIT_REPO}
    branch: master
    events: { "push": true }
  - type: manual
    name: manual-run
    eventListener: manual-run
    properties: []
properties:
  - type: secure
    name: toolchain-apikey
    value: ${API_KEY}
  - name: apikey
    value: ${API_KEY}
    type: SECURE
  - name: registry-region
    value: ${REGISTRY_REGION_ID}
    type: text
  - name: registry-namespace
    value: ${REGISTRY_NAMESPACE}
    type: text
  - name: image-name
    value: ${APP_NAME}-monitored-helm
    type: text
  - name: app-name
    value: ${APP_NAME}
    type: text
  - name: dev-cluster-namespace
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: dev-region
    value: ${PROD_REGION_ID}
    type: text
  - name: cluster-name
    value: ${PROD_CLUSTER_NAME}
    type: text
  - name: dev-resource-group
    value: ${PROD_RESOURCE_GROUP}
    type: text
  - name: GIT_URL
    value: ${GIT_URL}
    type: text
  - name: DEVX_SKIT_ASSETS_GIT
    value: ${DEVX_SKIT_ASSETS_GIT}
    type: text
  - name: DEVX_SKIT_ASSETS_GIT_RELEASE
    value: ${DEVX_SKIT_ASSETS_GIT_RELEASE}
    type: text
  - name: DEVX_SKIT_ASSETS_GIT_URL
    value: https://github.com/${DEVX_SKIT_ASSETS_GIT}.git
    type: text
  - name: DEVX_SKIT_ASSETS_GIT_URL_RAW
    value: https://github.com/${DEVX_SKIT_ASSETS_GIT}/raw/${DEVX_SKIT_ASSETS_GIT_RELEASE}
    type: text
  - name: DEVX_SKIT_ASSETS_GIT_URL_CODE
    value: https://codeload.github.com/${DEVX_SKIT_ASSETS_GIT}/tar.gz/${DEVX_SKIT_ASSETS_GIT_RELEASE}
    type: text
  - name: ENABLED_HELM
    value: ${ENABLED_HELM}
    type: text
  - name: HELM_CHART_NAME
    value: ${HELM_CHART_NAME}
    type: text
  - name: DEVX_SLACK_CHANNEL_WEBHOOK
    value: ${DEVX_SLACK_CHANNEL_WEBHOOK}
    type: secure
  - name: OWNER_SLACK_CHANNEL_WEBHOOK
    value: ${OWNER_SLACK_CHANNEL_WEBHOOK}
    type: secure
  - name: PAGERDUTY_API_URL
    value: ${PAGERDUTY_API_URL}
    type: text
  - name: PAGERDUTY_EVENTS_API_URL
    value: ${PAGERDUTY_EVENTS_API_URL}
    type: text
  - name: PAGERDUTY_API_TOKEN
    value: ${PAGERDUTY_API_TOKEN}
    type: secure
  - name: PAGERDUTY_SVC_NAME
    value: ${PAGERDUTY_SVC_NAME}
    type: secure
  - name: ENABLE_PD_ALERTS
    value: ${ENABLE_PD_ALERTS}
    type: text
  - name: SKIT_REG_ENDPOINT
    value: ${SKIT_REG_ENDPOINT}
    type: text
  - name: SKIT_REG_AUTH_TOKEN
    value: ${SKIT_REG_AUTH_TOKEN}
    type: secure
  - name: DEPLOY_TARGET
    value: helm
    type: text
  - name: DOCKER_USERNAME
    value: ${DOCKER_USERNAME}
    type: text
  - name: DOCKER_PASSWORD
    value: ${DOCKER_PASSWORD}
    type: secure
  - name: pipeline-debug
    type: single_select
    value:
      "0": true
      "1": false
settings:
  slackEnabled: true
