---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: skit-cleanup-helm
spec:
  params:
    - name: api-key
      description: IBM Cloud API key
    - name: app-name
      description: name of the helm app
    - name: cluster-name
      description: name of the kube cluster
    - name: pipeline-debug
      description: Pipeline debug mode. Value can be 0 (off) or 1 (on)
      default: "0"
  workspaces:
    - name: artifacts
      description: A workspace
      mountPath: /artifacts
  steps:
    - name: skit-cleanup-helm
      image: ibmcom/pipeline-base-image:2.13
      workingDir: /artifacts
      env:
        - name: API_KEY
          value: $(params.api-key)
        - name: APP_NAME
          value: $(params.app-name)
        - name: KUBE_CLUSTER
          value: $(params.cluster-name)
        - name: PIPELINE_DEBUG
          value: $(params.pipeline-debug)
      script: |
        #!/bin/bash
        set -e -o pipefail
        
        if [ $PIPELINE_DEBUG == 1 ]; then
            env
            pwd
            ls -l
            trap env EXIT
            set -x
        fi

        ibmcloud login -a "cloud.ibm.com" -r "us-south" --apikey "${API_KEY}" -g "devex-governance"
        
        ibmcloud ks config --cluster "${KUBE_CLUSTER}"
        echo "Deleteing Helm deployment: ${APP_NAME}..."
        kubectl delete deployment.apps/${APP_NAME}-deployment
        echo "Deleteing Helm service: ${APP_NAME}..."
        kubectl delete service/${APP_NAME}-application-service
