---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-cf
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
      default: "master"
    - name: revision
      description: the git revision/commit for the git repo (default to '' means branch)
      default: ""
    - name: region
      default: ""
    - name: apikey
      description: IBM Cloud API key
    - name: cf-org
    - name: cf-space
    - name: cf-app
    - name: GIT_URL
      description: the URL to the skit repo
    - name: DEVX_SKIT_ASSETS_GIT
      description: the org and repo containing skit assets
      default: "IBM/devex-skit-assets"
    - name: DEVX_SKIT_ASSETS_GIT_RELEASE
      description: the release version of the devex-skit-assets repo to use
    - name: DEVX_SKIT_ASSETS_GIT_URL
      description: the repo URL to the skit assets repo
    - name: DEVX_SKIT_ASSETS_GIT_URL_CODE
      description: the repo URL used to download skit asset releases
    - name: DEVX_SKIT_ASSETS_GIT_URL_RAW
      description: the repo URL used to download skit asset raw code
    - name: DEPLOY_TARGET
      description: the deployment target
      default: "cf"
    - name: SKIT_REG_ENDPOINT
      description: the skit registration endpoint URL
    - name: SKIT_REG_AUTH_TOKEN
      description: the skit registration authentication token
    - name: DEVX_SLACK_CHANNEL_WEBHOOK
      description: devx skit monitoring slack channel webhook
    - name: OWNER_SLACK_CHANNEL_WEBHOOK
      description: skit monitoring slack channel webhook for the skit owner (if different from devx)
    - name: ENABLE_PD_ALERTS
      description: whether or not to enable PagerDuty alerts
    - name: PAGERDUTY_EVENTS_API_URL
      description: PagerDuty Events API URL
    - name: PAGERDUTY_API_TOKEN
      description: PagerDuty API token
    - name: ENABLED_CF
      description: whether or not this pipeline is enabled
      default: "true"
    - name: pipeline-debug
      default: "0"
    - name: ibmcloud-api
      default: "https://cloud.ibm.com"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: cf-pipeline-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: cf-pipeline-$(uid)
      spec:
        pipelineRef:
          name: cf-pipeline
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: revision
            value: $(params.revision)
          - name: region
            value: $(params.region)
          - name: cf-org
            value: $(params.cf-org)
          - name: cf-space
            value: $(params.cf-space)
          - name: cf-app
            value: $(params.cf-app)
          - name: api-key
            value: $(params.apikey)
          - name: git-url
            value: $(params.GIT_URL)
          - name: devex-skit-assets-git
            value: $(params.DEVX_SKIT_ASSETS_GIT)
          - name: devex-skit-assets-git-release
            value: $(params.DEVX_SKIT_ASSETS_GIT_RELEASE)
          - name: devex-skit-assets-git-url
            value: $(params.DEVX_SKIT_ASSETS_GIT_URL)
          - name: devex-skit-assets-git-url-code
            value: $(params.DEVX_SKIT_ASSETS_GIT_URL_CODE)
          - name: devex-skit-assets-git-url-raw
            value: $(params.DEVX_SKIT_ASSETS_GIT_URL_RAW)
          - name: deploy-target
            value: $(params.DEPLOY_TARGET)
          - name: skit-reg-endpoint
            value: $(params.SKIT_REG_ENDPOINT)
          - name: skit-reg-auth-token
            value: $(params.SKIT_REG_AUTH_TOKEN)
          - name: devx-slack-channel-webhook
            value: $(params.DEVX_SLACK_CHANNEL_WEBHOOK)
          - name: owner-slack-channel-webhook
            value: $(params.OWNER_SLACK_CHANNEL_WEBHOOK)
          - name: enable-pd-alerts
            value: $(params.ENABLE_PD_ALERTS)
          - name: pagerduty-events-api-url
            value: $(params.PAGERDUTY_EVENTS_API_URL)
          - name: pagerduty-api-token
            value: $(params.PAGERDUTY_API_TOKEN)
          - name: enabled-cf
            value: $(params.ENABLED_CF)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: cf-pipeline-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: manual-run
spec:
  params:
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-run
spec:
  triggers:
    - binding:
        name: manual-run
      template:
        name: trigger-template-cf
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-commit
spec:
  params:
    - name: repository
      value: "$(event.repository.url)"
    - name: branch
      value: "$(event.ref)"
    - name: revision
      value: "$(event.head_commit.id)"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-commit
spec:
  triggers:
    - binding:
        name: github-commit
      template:
        name: trigger-template-cf
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: grit-or-gitlab-commit
spec:
  params:
    - name: repository
      value: "$(event.repository.git_http_url)"
    - name: branch
      value: "$(event.ref)"
    - name: revision
      value: "$(event.checkout_sha)"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: grit-or-gitlab-commit
spec:
  triggers:
    - binding:
        name: grit-or-gitlab-commit
      template:
        name: trigger-template-cf
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: bitbucket-commit
spec:
  params:
    - name: repository
      value: "$(event.repository.links.html.href)"
    - name: revision
      value: "$(event.push.changes[0].new.target.hash)"
    - name: branch
      value: "$(event.push.changes[0].new.name)"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: bitbucket-commit
spec:
  triggers:
    - binding:
        name: bitbucket-commit
      template:
        name: trigger-template-cf