---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-cf
spec:
  params:
    - name: repository
      description: The target git repo
    - name: branch
      description: the branch for the target git repo
      default: "master"
    - name: revision
      description: the git revision/commit for the target repo
    - name: pr-repository
      description: The git repo of the incoming changes
    - name: pr-branch
      description: the branch of the incoming changes
    - name: pr-revision
      description: the git revision/commit for the incoming changes
    - name: pr-url
      description: the URL for the PR for CRA tasks.
    - name: region
      default: ""
    - name: apikey
      description: IBM Cloud API key
    - name: cf-org
    - name: cf-space
    - name: cf-app
    # Helm parameters
    - name: fail-on-lint-errors
      description: force failure of task when docker lint errors are found
      default: "true"
    - name: registry-region
      description: The IBM Cloud region for image registry
    - name: registry-namespace
      description: container registry namespace
    - name: image-name
      description: image name
    - name: path-to-context
      default: "."
    - name: path-to-dockerfile
      default: "."
    - name: dockerfile
      default: "Dockerfile"
    - name: build-args
      description: ibmcloud cr build argument list in the format 'KEY=VALUE' with a key-value pair per line.
      default: ""
    - name: fail-on-scanned-issues
      description: force failure of task when vulnerability advisor scan issues are found
      default: "false"
    - name: helm-chart-path
      description: |
        path to the folder containing the helm chart content (at least Chart.yaml).
        If not specified, it will default to first folder in /chart
      default: ""
    - name: cluster-name
      description: the name of the cluster to target
    - name: dev-region
    - name: dev-resource-group
    - name: dev-cluster-namespace
      description: namespace dev
    - name: helm-upgrade-extra-args
      description: complementary argument for the helm upgrade command. Can be used to specify an additional values file
      default: ""
    - name: GIT_URL
      description: the URL to the skit repo
    - name: DEVX_SKIT_ASSETS_GIT
      description: the org and repo containing skit assets
      default: "IBM/devex-skit-assets"
    - name: DEVX_SKIT_ASSETS_GIT_RELEASE
      description: the release version of the devex-skit-assets repo to use
    - name: DEVX_SKIT_ASSETS_GIT_URL
      description: the repo URL to the skit assets repo
    - name: DEVX_SKIT_ASSETS_GIT_URL_CODE
      description: the repo URL used to download skit asset releases
    - name: DEVX_SKIT_ASSETS_GIT_URL_RAW
      description: the repo URL used to download skit asset raw code
    - name: HELM_CHART_NAME
      description: the name of the directory containing the helm chart
    - name: DEPLOY_TARGET
      description: the deployment target
      default: "cf"
    - name: APP_NAME
      description: the name of the skit being monitored
    - name: SKIT_REG_ENDPOINT
      description: the skit registration endpoint URL
    - name: SKIT_REG_AUTH_TOKEN
      description: the skit registration authentication token
    - name: DEVX_SLACK_CHANNEL_WEBHOOK
      description: devx skit monitoring slack channel webhook
    - name: OWNER_SLACK_CHANNEL_WEBHOOK
      description: skit monitoring slack channel webhook for the skit owner (if different from devx)
    - name: ENABLE_PD_ALERTS
      description: whether or not to enable PagerDuty alerts
    - name: PAGERDUTY_EVENTS_API_URL
      description: PagerDuty Events API URL
    - name: PAGERDUTY_API_TOKEN
      description: PagerDuty API token
    - name: ENABLED_CF
      description: whether or not this pipeline is enabled
      default: "true"
    - name: ENABLED_HELM
      description: whether or not helm is enabled
      default: "true"
    - name: DOCKER_USERNAME
      description: Docker login username
    - name: DOCKER_PASSWORD
      description: Docker login password
    - name: pipeline-debug
      default: "0"
    - name: ibmcloud-api
      default: "https://cloud.ibm.com"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: cf-pipeline-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: cf-pipeline-$(uid)
      spec:
        pipelineRef:
          name: cf-pipeline
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: revision
            value: $(params.revision)
          - name: pr-repository
            value: $(params.pr-repository)
          - name: pr-branch
            value: $(params.pr-branch)
          - name: pr-revision
            value: $(params.pr-revision)
          - name: pr-url
            value: $(params.pr-url)
          # CF Parameters
          - name: region
            value: $(params.region)
          - name: cf-org
            value: $(params.cf-org)
          - name: cf-space
            value: $(params.cf-space)
          - name: cf-app
            value: $(params.cf-app)
          - name: api-key
            value: $(params.apikey)
          # Helm Parameters
          - name: fail-on-lint-errors
            value: $(params.fail-on-lint-errors)
          - name: registry-region
            value: $(params.registry-region)
          - name: registry-namespace
            value: $(params.registry-namespace)
          - name: image-name
            value: $(params.image-name)
          - name: path-to-context
            value: $(params.path-to-context)
          - name: path-to-dockerfile
            value: $(params.path-to-dockerfile)
          - name: dockerfile
            value: $(params.dockerfile)
          - name: build-args
            value: $(params.build-args)
          - name: fail-on-scanned-issues
            value: $(params.fail-on-scanned-issues)
          - name: helm-chart-path
            value: /artifacts/helm/$(params.APP_NAME)/chart/$(params.HELM_CHART_NAME)
          - name: dev-region
            value: $(params.dev-region)
          - name: dev-resource-group
            value: $(params.dev-resource-group)
          - name: cluster-name
            value: $(params.cluster-name)
          - name: dev-cluster-namespace
            value: $(params.dev-cluster-namespace)
          - name: helm-upgrade-extra-args
            value: $(params.helm-upgrade-extra-args)
          #
          - name: git-url
            value: $(params.GIT_URL)
          - name: devex-skit-assets-git
            value: $(params.DEVX_SKIT_ASSETS_GIT)
          - name: devex-skit-assets-git-release
            value: $(params.DEVX_SKIT_ASSETS_GIT_RELEASE)
          - name: devex-skit-assets-git-url
            value: $(params.DEVX_SKIT_ASSETS_GIT_URL)
          - name: devex-skit-assets-git-url-code
            value: $(params.DEVX_SKIT_ASSETS_GIT_URL_CODE)
          - name: devex-skit-assets-git-url-raw
            value: $(params.DEVX_SKIT_ASSETS_GIT_URL_RAW)
          - name: deploy-target
            value: $(params.DEPLOY_TARGET)
          - name: skit-name
            value: $(params.APP_NAME)
          - name: skit-reg-endpoint
            value: $(params.SKIT_REG_ENDPOINT)
          - name: skit-reg-auth-token
            value: $(params.SKIT_REG_AUTH_TOKEN)
          - name: devx-slack-channel-webhook
            value: $(params.DEVX_SLACK_CHANNEL_WEBHOOK)
          - name: owner-slack-channel-webhook
            value: $(params.OWNER_SLACK_CHANNEL_WEBHOOK)
          - name: enable-pd-alerts
            value: $(params.ENABLE_PD_ALERTS)
          - name: pagerduty-events-api-url
            value: $(params.PAGERDUTY_EVENTS_API_URL)
          - name: pagerduty-api-token
            value: $(params.PAGERDUTY_API_TOKEN)
          - name: enabled-cf
            value: $(params.ENABLED_CF)
          - name: enabled-helm
            value: $(params.ENABLED_HELM)
          - name: docker-username
            value: $(params.DOCKER_USERNAME)
          - name: docker-password
            value: $(params.DOCKER_PASSWORD)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: cf-pipeline-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: manual-run
spec:
  params:
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-run
spec:
  triggers:
    - binding:
        name: manual-run
      template:
        name: trigger-template-cf
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-github-pr-or-push
spec:
  params:
    - name: repository
      value: "$(event.pull_request.base.repo.clone_url)"
    - name: branch
      value: "$(event.pull_request.base.ref)"
    - name: revision
      value: "$(event.pull_request.base.sha)"
    - name: pr-repository
      value: "$(event.pull_request.head.repo.clone_url)"
    - name: pr-branch
      value: "$(event.pull_request.head.ref)"
    - name: pr-revision
      value: "$(event.pull_request.head.sha)"
    - name: pr-url
      value: "$(event.pull_request.html_url)"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-commit
spec:
  triggers:
    - binding:
        name: trigger-binding-github-pr-or-push
      template:
        name: trigger-template-cf